### PR TITLE
Ice sheet mask comparison scripts

### PR DESCRIPTION
**Pull request by lvankampenhout**

### CODE REVIEW

**Comment by billsacks** [comment]
@lvankampenhout Thanks for opening a PR for these scripts. These would be helpful to have. However, I'm a bit wary of including binary files (i.e., the netCDF files) in the git repo: my understanding is that git doesn't do versioning of binary files very well, and these bloat the repo. Do you feel that it's important that these netcdf files be included in this repo, or would it still be useful to have the scripts here without the netcdf files... perhaps with a pointer to the relevant files?

**Comment by lvankampenhout** [comment]
Hi Bill, I see your point about the binary files. I just had a look at the UNIX scripts and I don't think they're really worth maintaining. Let's leave it be for now.

**Comment by billsacks** [comment]
@lvankampenhout so do you suggest that we close this PR without merging?

**Comment by lvankampenhout** [comment]
whoops, sorry for my unclear answer. Yes that is my suggestion.

**Pull request closed without merging**
